name: "Docker Build and Push"

on:
  workflow_dispatch:
jobs:
  build:
    name: Setup
  
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: QEMU Setups
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      -
        name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Bake and Push
        run: docker buildx bake --push
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_BUILD_ARGS: --build-arg BUILDKIT_INLINE_CACHE=1
          DOCKERFILE: Dockerfile
          PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
          TARGET: ghcr.io/${{ github.repository }}
          TAG: latest
          CONTEXT: .
          BUILDX: default
          BAKEFILE: docker-bake.hcl
          DOCKER_CLI_EXPERIMENTAL: enabled
