name: "Docker Build and Push"

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Free space on runner
        run: rm -rf /opt/hostedtoolcache
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: QEMU Setups
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PAT }}
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          targets: "default"
